### ISSUE TITLE
Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' 

### ISSUE THREAD

**Issue by Vanerac** [Vanerac/drake-issues#1]
```
2|Drake    | Unhandled Rejection at: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list'
2|Drake    |     at Query.Sequence._packetToError (/home/pi/Drake/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
2|Drake    |     at Query.ErrorPacket (/home/pi/Drake/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
2|Drake    |     at Protocol._parsePacket (/home/pi/Drake/node_modules/mysql/lib/protocol/Protocol.js:278:23)
2|Drake    |     at Parser.write (/home/pi/Drake/node_modules/mysql/lib/protocol/Parser.js:76:12)
2|Drake    |     at Protocol.write (/home/pi/Drake/node_modules/mysql/lib/protocol/Protocol.js:38:16)
2|Drake    |     at Socket.<anonymous> (/home/pi/Drake/node_modules/mysql/lib/Connection.js:91:28)
2|Drake    |     at Socket.<anonymous> (/home/pi/Drake/node_modules/mysql/lib/Connection.js:502:10)
2|Drake    |     at Socket.emit (events.js:182:13)
2|Drake    |     at Socket.EventEmitter.emit (domain.js:442:20)
2|Drake    |     at addChunk (_stream_readable.js:280:12)
2|Drake    |     at readableAddChunk (_stream_readable.js:265:11)
2|Drake    |     at Socket.Readable.push (_stream_readable.js:220:10)
2|Drake    |     at TCP.onread (net.js:638:20)
2|Drake    |     --------------------
2|Drake    |     at Protocol._enqueue (/home/pi/Drake/node_modules/mysql/lib/protocol/Protocol.js:144:48)
2|Drake    |     at PoolConnection.query (/home/pi/Drake/node_modules/mysql/lib/Connection.js:200:25)
2|Drake    |     at /home/pi/Drake/node_modules/promise-mysql/lib/helper.js:16:24
2|Drake    |     at Promise._execute (/home/pi/Drake/node_modules/bluebird/js/release/debuggability.js:303:9)
2|Drake    |     at Promise._resolveFromExecutor (/home/pi/Drake/node_modules/bluebird/js/release/promise.js:483:18)
2|Drake    |     at new Promise (/home/pi/Drake/node_modules/bluebird/js/release/promise.js:79:10)
2|Drake    |     at PoolConnection.promiseCallback (/home/pi/Drake/node_modules/promise-mysql/lib/helper.js:6:10)
2|Drake    |     at poolConnection.connection.query (/home/pi/Drake/node_modules/promise-mysql/lib/connection.js:64:28)

```

**Comment by Vanerac** [comment]
https://github.com/mysqljs/mysql/issues/1716

**Comment by Vanerac** [comment]
`Message timestamp:Sat Sep 01 2018 19:27:09 GMT+0000 (UTC) User: Pakinus UPDATE users SET xp = NaN, Level = NaN WHERE UserId = '437680029577510923' AND ServerID = '484851075677945866'`

**Comment by Vanerac** [comment]
c'est que @pakinus

**Comment by Vanerac** [comment]
c'est pas pakinus

**Comment by Vanerac** [comment]
probleme: essaye de modifier une valeur inconnue (membre ou autre qui n'est pas dans la DB )
